# Pre-conference events

::: {.callout-tip icon=false}
## **Registration is open**

Each event spans two days. Participants should register for **either** the workshop or the hackathon.

Register for  
- Workshop registration form becomes available shortly  
- [Hackathon](https://docs.google.com/forms/d/e/1FAIpQLSdQPwHgF7fJwfwkXxKPZeB5W_MjTMQpjLbRZj1ix-bA4vLYOg/viewform?usp=header)

<!--
- [Workshop](https://portal.lyyti.fi/reg16/?p=choose&uid=1f10ccde-d871-60b2-9c74-47c5a587250c)  
-->

Registration closes on **Sunday, May 3**, or earlier if capacity is reached.
:::

## Fees

| Type                                  |   Fee    |
|:--------------------------------------|:--------:|
|Workshop (includes lunches)            | **€100** |
|Hackathon                              | **free** |

::: {.callout-note icon=false}
## **Workshop fee**

If you are unable to pay the fee, you may request to be added to a waiting list
in case funding becomes available. Please note that places will be filled on a
first‑come, first‑served basis by paying participants. If all places fill before
funding becomes available, we may not be able to offer you a spot.
:::

## Event descriptions

Before the conference, on **Monday and Tuesday, 1–2 June**, the
[Bioconductor Training Committee](https://training.bioconductor.org), in
collaboration with the [University of Turku](https://www.utu.fi),
[CompLifeSci](https://biocityturku.fi/research-programs/complifesci/), and
[the Finnish Society for Bioinformatics](https://www.bioinf.fi/), will organize
the following two-day pre-conference events:

1. **Workshop: Orchestrating Microbiome Analysis with Bioconductor**  
2. **Hackathon**  

### 1. **Orchestrating Microbiome Analysis with Bioconductor**
This is a **Bioconductor Carpentries workshop**, combining the Carpentries’
hands-on, interactive teaching approach with Bioconductor-specific materials.  

Over 2 days, participants will learn how to:  

* Import, process, and analyze microbiome datasets  
* Explore diversity patterns  
* Perform differential abundance analyses  
* Integrate multi-omics data  

The course combines lectures with practical exercises to give participants the
skills and confidence to run common microbiome analysis workflows independently
using freely available resources.  

**Prerequisites:** Familiarity with R and Bioconductor

**Instructors:** Leo Lahti, Himel Mallick and Tuomas Borman

#### What is a Bioconductor Carpentry Workshop

[The Carpentries](https://carpentries.org) is a global community focused on
teaching foundational coding and data science skills to researchers. The core
of this community are
[Carpentries Instructors](https://carpentries.org/community/instructors), who
work together to grow their instructional and technical skills. Bioconductor is
a member of The Carpentries, supporting community members to earn Carpentries
instructor certification, develop Bioconductor-specific training materials, and
teach Carpentry workshops on those materials.

A Bioconductor Carpentry Workshop is a course on how to use Bioconductor
packages and workflows, led by Carpentry-certified instructors on materials
developed by the Bioconductor community.

### 2. **Hackathon**
A bioconductor-centric hackathon will be held in the two days before
EuroBioc2026. Currently proposed topics include:

* An R package for CUDA API bindings, to facilitate development and access to
CUDA natively in R, package name TBD
* A tool for building minimal, lightweight containers for bioconductor packages
on the fly, from the package dependency graph
* A package or function for converting R scripts into commandline executables,
with an emphasis on robust and reliable deployment
* A tidy / spatial -omics project, TBD

Participants are welcome to bring or propose their own topics as well. Support
for general bug hunting or feature additions in existing packages that are 
willing to accept pull requests will also be supported.

Bioconductor is a mature, diverse, and well-maintained project with many
different ways to contribute. Participants from all career stages and technical
backgrounds are welcome, with the only requirements being a willingness to
learn and work well in a collaborative environment.

We will be in contact about a month before the conference to confirm
participation, plan out teams for projects, and ensure any questions or concerns
are addressed.

Hackathon goals can vary widely depending on project complexity, but in general
working and tested R packages are the goal where applicable. Tangible
contributions to repositories that can be clearly professionally communicated
will be the goal otherwise.

## Venue and requirements

Both pre-conference events will take place at the **EuroBioC2026 venue**.  
Participants are expected to bring a laptop. The rooms will provide:  

* Electrical outlets for laptops  
* Wireless internet (Eduroam WiFi available)

## Questions?

If you have any questions about the pre-conference workshop or hackathon,
do not hesitate to contact the [organizers](organizers.html) at
[eurobioc@bioconductor.org](mailto:eurobioc@bioconductor.org).
