# Submissions

## Call for abstracts

::: {.callout-important icon=false}
## **Abstract call closed**

**Important dates**

- **November 24**: Call for abstracts opens
- ~~**January 30**: Call for abstracts closes~~
- **February 13**: Call for abstracts closes (final extended deadline)

<!--
[Submit your abstract here!](https://openreview.net/group?id=bioconductor.org/EuroBioC/2026/Conference){target="_blank"}
-->

:::

::: callout-important

The submission system requires all submitters to create an account.
If you do not already have an account in _OpenReview_, we strongly
recommend doing this at least **two weeks before** the
abstract deadline. This is especially important for non-academic
institutions, as account verification may take some time.

If you are submitting close to the deadline, you are still very
welcome to do so! Please create your account as soon as possible.
Academic accounts typically do not experience any delays, but early
profile creation is encouraged for everyone.

If you encounter any issues, please contact us at
[eurobioc@bioconductor.org](mailto:eurobioc@bioconductor.org)

:::

## Submission types

### Short talk

Around 10 min short talk immediately followed by questions, focused on a
package, or on a research or technological question that motivates software
development. Presentations seeking collaboration or input from the community
are encouraged.

### Poster

Classical portrait printed A0-poster to be showcased during poster session.

### Workshop

Around 1.5 hour hands-on interactive workshop illustrating the use of a software
package or workflow, where participants are expected to have the time and
opportunity to follow along and perform analysis themselves.

### Flash talk

Flash talks are very short presentations (5 min or less) that may be submitted
up until the day of the session, granted on a first come, first served basis.

Slides must be either publicly accessible online or uploaded to a shared Google
Drive. Presenters will not be allowed to connect their own laptop. We advise
presenters to keep presentations simple (e.g., avoid animations where possible).

Conference delegates already scheduled to present a short talk or poster are
welcome to submit flashtalks.

### Birds-of-a-feather

Birds-of-a-feather sessions are free-format, organizer-lead interactive
discussions on a topic relevant to the Bioconductor community.
Birds-of-a-feather sessions should be proposed before the beginning of the
conference, by filing an issue in <https://github.com/Bioconductor/EuroBioC2026>.

In the issue, please provide information about the plan and intended outcomes
of the session, as well as the name and contact information of the organizer(s).
You may refer to <https://github.com/Bioconductor/EuroBioC2025/issues> for
examples submitted last year.

## Pre-conference workshops

::: {.callout-important icon=false}
## **Call for pre-conference workshops closed**

**Important dates**

- **December 5**: Call for pre-conference workshops opens
- **January 30**: Call for pre-conference workshops closes

<!--
[Please submit your interest here!](https://docs.google.com/forms/d/e/1FAIpQLScYOBMs0JsmoZY21mCSnWSBObm-OX7NtZi6NEjY9zNdhsqL5w/viewform){target="_blank"}
-->

:::

On-site workshops on June 1–2, 2026, in Turku, Finland, prior to the main
conference. Please note that these workshops are **separate from the main
conference workshops**.

If you’re interested in hosting a workshop, please submit your interest.
Selections will be based on relevance and alignment with the workshop and
conference themes.

## Questions?

Do not hesitate to contact the [organizers](organizers.html) at
[eurobioc@bioconductor.org](mailto:eurobioc@bioconductor.org) if you have
a question about an abstract submission.
