# Travel Information

## Conference venue

The European Bioconductor Conference 2026 will be held in **Turku, Finland**.

The venue is the **[BioCity Turku building](https://biocityturku.fi/){target="_blank"}**
(address: Tykistökatu 6, Turku).

```{r}
#| label: map
#| echo: false
#| message: false
#| warning: false

source(file.path("..", "R", "create_a_map.R"))
create_a_map()
```

## How to travel to Turku

In Turku and the Southwest Finland region, it’s easy for travellers to get
around using public transportation. Cities and towns have efficient local
transit systems, and longer distances can comfortably be covered by
long-distance buses and trains. Turku also has a passenger ferry terminal and an
international airport.

### Helsinki Airport

If you arrive via **Helsinki Airport**, there are two good options to reach
Turku:

- **Direct bus from the airport:** Direct buses to Turku
(travel time: 2–2.5 hours) are operated by Matkahuolto and leave approximately
every second hour. The tickets can be bought from Matkahuolto website or from
buses. See [time table](https://www.matkahuolto.fi/en/){target="_blank"}.

- **Train:** Take a commuter train from the airport to Pasila Station in
Helsinki, then transfer to a direct train to Turku. Trains run about once an
hour between 5:00 a.m. and 8:30 p.m. Total travel time is around 2.5 hours. The
tickets can be bought from [VR website](https://www.vr.fi/en){target="_blank"}
or from kiosk from train platform. The train stops at Kupittaa station, next to
Original Sokos Hotel Kupittaa hotel and the conference venue.

- **Travel to Helsinki and take bus to Turku:** As direct bus connections are
limited, you might consider taking a train or bus to Helsinki city centre where
buses leave frequently to Turku. See
[HSL website](https://www.hsl.fi/en){target="_blank"}
for connections and tickets to Helsinki city centre. Then consult
[Matkahuolto website](https://www.matkahuolto.fi/en/){target="_blank"}
for buses to Turku.

::: callout-tip
Flying to Helsinki is likely the easiest and most convenient option. Then
you can take the train that stops at Kupittaa station; next to
Original Sokos Hotel Kupittaa hotel and the conference venue.
:::

### Turku Airport

Turku has an international airport with flights from cities such as Stockholm,
Copenhagen, Riga, Bucharest, Vilnius, and Gdansk. From the airport (approx. 8 km
from the city centre), bus no. 1 runs approximately every 20 minutes.

- Tickets cost €3.15 (€4.15 between 11 p.m. and 4 a.m.)
- Tickets are available via the mobile app or with contactless payment from the
driver.

More information about bus tickets from the airport can be found
[here](https://www.foli.fi/en/tickets){target="_blank"}.

A taxi to the city centre costs approximately €20. All taxis accept credit and
debit cards.

**Taxi Turku:** [+358 200 10041](tel:+35820010041)  
There are several taxi stands in the city centre.

### Ferry

From Stockholm, Sweden, you can travel to Turku by ferry through one of the
most beautiful archipelagos in the world. Daily services between Stockholm and
Turku are operated by [Tallink Silja](https://en.tallink.com/book-a-cruise){target="_blank"} and
[Viking Line](https://www.sales.vikingline.com/){target="_blank"}. The journey
takes approximately 10 hours. Another option is Finnlines, offering comfortable
ferry travel between Kapellskär (Sweden) and Naantali (located only 15 km from
Turku and easily reached by car or taxi).

From Turku harbour, bus line no. 1 operates regularly (every 10–20 minutes)
to the city centre (approx. 3 km). A single ticket cost €3.15 (€4.15 between
11 p.m. and 4 a.m.) and can be purchased via the mobile app, or directly from
the driver using contactless payment. More information can be found
[here](https://www.foli.fi/en/tickets){target="_blank"}.

From Turku Harbour, you can also take a train directly to Turku Central Railway
Station – just a 15-minute walk from the city centre – or to Kupittaa Railway
Station, located only a few hundred metres from the conference venue, BioCity.
Check train schedules [here](https://www.vr.fi/en){target="_blank"}.

::: callout-tip
Flying to Stockholm and then taking a ferry to Turku is the most
unique&mdash;and still very reasonable&mdash;option. Along the way, you can
relax and enjoy views of the world’s largest archipelago.
:::

## Local transportation

Turku is a rather small city and everything is nearby. The public
transportation, known as Föli, is an efficient way to get around&mdash;you can
take a bus or rent a bike. More information is available
[here](https://www.foli.fi/en){target="_blank"}. Turku is also very walkable,
and you can easily get around the city on foot.

::: callout-tip
All participants get public transportation pass which you can use 3-5 of June to travel with public transportation for free. The pass is printed in your conference name badge.
:::

## Transport links  

- [Air Baltic](https://www.airbaltic.com/en-FI/index){target="_blank"}  
  Airline information and timetables
  
- [Finnair](https://www.finnair.com/choose-country-language?locale=en_INT){target="_blank"}  
  Airline information and timetables
  
- [Finnlines](https://www.finnlines.com/routes/naantali-kapellskar/){target="_blank"}  
  Ferryboat connections from Kapellskär

- [Föli](https://www.foli.fi/en){target="_blank"}  
  Turku public transport

- [HSL](https://www.hsl.fi/en){target="_blank"}  
  Helsinki public transport
  
- [Matkahuolto](https://www.matkahuolto.fi/en/){target="_blank"}  
  Finnish long-distance buses

- [Onnibus](https://www.onnibus.com/home){target="_blank"}  
  Finnish long-distance buses

- [SAS](https://www.sas.fi/en/){target="_blank"}  
  Airline information and timetables
  
- [Tallink Silja](https://www.tallinksilja.com){target="_blank"}  
  Ferryboat connections from Stockholm

- [The Finnish Rail (VR)](https://www.vr.fi/en){target="_blank"}  
  Timetables, train connections

- [Viking Line](https://www.sales.vikingline.com/){target="_blank"}  
  Ferryboat connections from Stockholm

- [Wizz Air](https://wizzair.com/en-gb#/){target="_blank"}  
  Airline information and timetables

## Staying in Turku

### The nearest hotel

Below is a brief introduction to a hotel offering a special room rate for
participants of the European Bioconductor Conference 2026.
**Please make your booking directly to the hotel**, see contact details below.
The hotel fees include breakfast, service and VAT.
**The hotel fee is to be paid directly to the hotel**.
Please note that the rooms can only be booked according to the hotel’s booking
situation and
**we encourage you to make the hotel reservations well in advance**.
Please be cautious of any contacts from parties claiming to arrange travel or
accommodation for the conference participants. We mention this as a precaution
against phishing attempts, which are common nowadays.
We hope you will enjoy your stay in Turku!

**Original Sokos Hotel Kupittaa**  
**Joukahaisenkatu 6, 20520 Turku**  
**+358 300 870 000**  
[sokos.hotels@sok.fi](mailto:sokos.hotels@sok.fi)  
[Hotel website](https://www.sokoshotels.fi/en/hotels/turku/original-sokos-hotel-kupittaa){target="_blank"}

**Original Sokos Hotel Kupittaa** is a modern hotel located right in the heart
of Kupittaa, a fast-growing area in Turku. The atmosphere at the hotel is
relaxed, while stylish, and the hotel staff go above and beyond to ensure your
comfort. 

After a full day at the conference, unwind in the scenic landscape sauna or take
in the views from the Kuppis Rooftop Bar. Additional amenities include a
fitness room, a car park, and dining options for breakfast, lunch, and dinner. 

The hotel offers added convenience of direct access to the Kupittaa railway
station.
The city centre is easily accessible on foot, by Fölläri city bikes, or by
local bus from the bus stop located right outside the hotel.

Standard Single room € 124 per night  
Standard Twin room € 144 per night

**Reservations** can be made using the booking code
(**code will be sent by email for registered**) on the website, or the
booking code by phone or email to the hotel using the contact details above.

Please note that the reservations in Original Sokos Hotel Kupittaa must be made
by 20 May 2026 or based on availability.

::: {.callout-caution icon=false}
## Availability notice (updated 26 March 2026)

Availability is very limited for Tuesday night and rooms may no longer be
available. From Wednesday to Friday, availability is better and rooms should
still be obtainable.
:::

### Reservations

Reservations can be made using the booking code (**code will be sent by email for registered participants**) on the website, or by phone or email using the contact details above.

::: {.callout-caution icon=false}
## Notice (updated April 7, 2026)

Please note that reservations must be made by **2 May 2026**.
:::

### Other accommodation options

In city centre, there are many other accommodation options. City centre is about
30 minutes walk or 15 minutes bus drive away from the venue. In addition to
hotels, [Airbnb](https://www.airbnb.co.uk/s/Turku--Suomi/homes?refinement_paths%5B%5D=%2Fhomes&place_id=ChIJu9uOgYR1jEYRAMJLVVG1AAQ&location_bb=QnIe8UGzDktCcVWeQbCIEg%3D%3D&acp_id=672085f3-0188-4003-b3a5-87ffc64fb213&date_picker_type=calendar&checkin=2026-06-02&checkout=2026-06-05&search_type=unknown&_set_bev_on_new_domain=1768551078_EANDE2YWVkMzI5ZT&set_everest_cookie_on_new_domain=1768551078.EAZDZkYzc1MDA2MTBjYW.QodjEX3puOV6t4G1pAfUebDJwa6NYPM4gETauglCwoc){target="_blank"},
[Booking.com](https://www.booking.com/searchresults.en-gb.html?ss=Turku&ssne=Turku&ssne_untouched=Turku&label=gog235jc-10CAMoSEIFdHVya3VIDFgDaEiIAQGYATO4ARnIAQ_YAQPoAQH4AQGIAgGoAgG4Av7jp8sGwAIB0gIkMmE3Nzk2NTAtNzMzNy00NjlhLTgxOWEtY2ZkYjE5Nzk4OTA12AIB4AIB&aid=356980&lang=en-gb&sb=1&src_elem=sb&src=searchresults&dest_id=-1389822&dest_type=city&checkin=2026-06-02&checkout=2026-06-05&group_adults=2&no_rooms=1&group_children=0&soz=1&lang_changed=1){target="_blank"}
and other similar options are available.

Below are listed some of them.

- [Bore](https://cloud.hotellinx.com/NetReservationsBore/Home/Availability){target="_blank"}  
  Hostel in a 1960s cruise ship. In a harbour, so little bit more far away
  (the venue can be reached in 35 minutes by bus). Unique and affordable option,
  own cabin and breakfast included.

- [Centro Hotel](https://centrohotel.com/en/){target="_blank"}  
  Hotel

- [Forenom Aparthotel](https://www.forenom.com/aparthotels/turku/forenom-aparthotel-turku/411/?checkin=%222026-06-02%22&checkout=%222026-06-05%22&occupants=1){target="_blank"}  
  Aparthotel
  
- [Omena Hotel, Humalistonkatu](https://www.omenahotels.com/en/hotels/turku-humalistonkatu-en/){target="_blank"}  
  Hotel
  
- [Omena Hotel, Kauppiaskatu](https://www.omenahotels.com/en/services/omena-hotel-turku-kauppiaskatu/){target="_blank"}  
  Hotel

- [Scandic Hamburger Börs](https://www.scandichotels.com/en/hotelreservation/select-rate?room%5B0%5D.adults=1&fromdate=2026-06-02&todate=2026-06-05&city=Turku&hotel=640){target="_blank"}  
  Hotel

- [Scandic Julia](https://www.scandichotels.com/en/hotelreservation/select-rate?room%5B0%5D.adults=1&fromdate=2026-06-02&todate=2026-06-05&hotel=619){target="_blank"}  
  Hotel
  
- [Scandic Plaza](https://www.scandichotels.com/en/hotelreservation/select-rate?room%5B0%5D.adults=1&fromdate=2026-06-02&todate=2026-06-05&hotel=629){target="_blank"}  
  Hotel

- [Sokos Hotel Seurahuone](https://www.sokoshotels.fi/en/hotels/turku/solo-sokos-hotel-turun-seurahuone){target="_blank"}  
  An elegant and lively boutique hotel located in the heart of Turku, just a few
  blocks from the Turku Market Square. Special rates are available for
  participants. Reservations can be made using the booking code (included in the
  registration confirmation or available on request).

  Rates: 155 EUR / night (single), 175 EUR / night (double)  

- [Sokos Hotel Wiklund](https://www.sokoshotels.fi/en/hotels/turku/original-sokos-hotel-wiklund){target="_blank"}  
  Hotel
  
## Tips about Turku

See tips about Turku on the [About Turku](about-turku.qmd) page.
